### ISSUE TITLE
Missing a dependency?

### ISSUE THREAD

**Issue by amirebrahimi** [schellingb/sizer-net#1]
Most Unity assemblies will reference UnityEditor or UnityEngine, which in my test failed to load, which forced a close of the program. Is it possible to still show the assembly sizes with dependencies missing?

**Comment by schellingb** [comment]
Good point!
It worked in cases where the all dependency DLLs were in the same directory as the inspected assembly but otherwise it failed.
I just updated the tool to [v1.1](/schellingb/sizer-net/releases/tag/v1.1), now it shows another file selection dialog for each dependency that can't be resolved. One can cancel out of this selection but it will probably lead to unresolvable types during the size counting which will end up being counted in the 'Other Overhead' entry (along an error message).

**Comment by amirebrahimi** [comment]
Thanks! Works for me now.
